# version: '3.8' 불필요: 최신 Docker Desktop이나 docker compose CLI는 Compose Specification (스펙) 를 따릅

services:
  mysql:
    image: mysql:8.0
    container_name: cleopatra-mysql
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - my-network
    deploy:
      resources:
        limits:
          memory: 800M    # MySQL 메모리 최대 800MB 제한
        reservations:
          memory: 400M    # MySQL 최소 예약 메모리 400MB
    cpu_shares: 512     # CPU 우선순위 (기본 1024), 512는 절반 정도 할당

  mongo:
    image: mongo:7.0
    container_name: cleopatra-mongo
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL","mongosh --quiet --eval 'db.adminCommand({ping:1}).ok' | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    cpu_shares: 256

  application:
    image: kimgt2828/cleopatra-server:latest
    #build: .
    container_name: cleopatra-application
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: cleopatra-nginx
    restart: always
    ports:
      - "80:80"  # HTTP 요청을 80번 포트에서 받음
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # 설정 파일 마운트
    depends_on:
      - application
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data: