spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        highlight_sql: false

  data:
    mongodb:
      #uri: mongodb://${MONGO_APP_USERNAME}:${MONGO_APP_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
      uri: mongodb://${MONGO_APP_USERNAME}:${MONGO_APP_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=${MONGO_AUTH_DB:${MONGO_DB}}
      auto-index-creation: false

logging:
  level:
    org.hibernate.SQL: error
    org.hibernate.type.descriptor.sql: error
    root: info
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.mongodb.driver: WARN

springdoc:
  packages-to-scan: com.likelion.cleopatra
  paths-to-match: /api/**
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8