name: CI

on:
  pull_request:
  push:
    branches:
      - 'dev'

jobs:
  build:
    name: "Check Gradle Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: true

      - name: Update Git submodules
        run: git submodule update --remote --recursive

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant Execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle excluding tests
        run: ./gradlew clean build -x test
